### ISSUE TITLE
Change the plugin model to be job agnostic

### ISSUE THREAD

**Issue by eyakubovich** [appc/cni#10]
I am creating this issue to summarize @thockin's comments on https://github.com/appc/cni/pull/2. In particular, Tim's proposed to make the spec less opinionated. Current spec defines a network as a group of containers that are able to talk to each other. The user defines which networks a given container needs to join. The container runtime executes a plugin for each network and the job of said plugin is to join the container to the network. As such, there's an assumption that a plugin will create an interface, assign it an IP, etc.

Tim proposes to have the container runtime call out to a plugin (or maybe multiple) and the plugin can do whatever it wants. For example, you can have a plugin to setup IP Masquerade or to block some traffic or change an IP of an existing interface.

Tim's proposal is quite flexible but also a fundamental shift from the current spec. I'd like to discuss this further and also schedule a hangout for Fri or next week: http://doodle.com/arqu4y9rgt9ybfp3

**Comment by steveeJ** [comment]
The proposal seems very vague and personally for me not enough to form an opinion about it. What would help is a comparison of the current situation and the changes the proposal would make to it.

**Comment by eyakubovich** [comment]
Hangout on Tue May 12th, at 2:00PM Pacific Time. 	https://plus.google.com/hangouts/_/coreos.com/cni-model

**Comment by jainvipin** [comment]
@eyakubovich - I will be there in the hangout. While it might seem vague to some, I think if you are allowing a plugin to do whatever it likes for network, I like @thokin's idea, leave it to the plugin with the right hooks (call them before container is launched, etc.) and then there full liberty/flexibility given to the plugin - as the network intent is driven from it. This is what was proposed as hook for Kubernetes and works fine with for my use cases.

**Comment by eyakubovich** [comment]
Thank @jonboulle for taking minutes: https://docs.google.com/document/d/1RRgRhSM2_r68XZuJfOhU3sUR99lnOzRWyCAE8-HTVBA

**Comment by eyakubovich** [comment]
I think the basic takeaways from this meeting were:
- There's much conceptual overlap with CNM/libnetwork -- we should explore collaboration
- Having a plugin do a particular job of plugging container into a network is OK
- Prescribing interface name to the plugin is excessive
- There's a desire to introduce Network Create event. However, it is still unclear if this event needs to be triggered on a single node in the cluster or on every node.
- @jainvipin will file an issue with proposed policy based straw man.

**Comment by Symmetric** [comment]
From the minutes, it looks like @philips was concerned that CNM drivers need to be in-tree. I'd like to chime in with what we've learned of the current plans there, since we've been doing a lot of digging into the CNM and it sounds like this concern might be misplaced (or the minutes might not have captured the full discussion, apologies if I've missed something).

The network driver is a container which gets spun up by the docker [plugin mechanism](https://github.com/docker/docker/blob/master/pkg/plugins/plugins.go). As currently implemented plugins are Docker containers, but there's no reason the underlying network API should depend on that. 

In a bit more detail, the current plugin code waits for the plugin container to create a Unix socket in a well-known location, and then uses that socket to initiate a handshake with the driver over an HTTP API. The driver then reports what type of driver it is (storage, network, ...), and then is ready to service requests from libnetwork.

It sounds like this is a big departure from the CNI way (much more proscribed), but I don't think there is a requirement for CNM network drivers to be Go code running inside the docker daemon.

Possibly worth mentioning, another impedance mismatch between the proposals is the Endpoint vs. Sandbox distinction; in CNM, there is a logical step to create the Endpoint (potentially globally for the cluster), then in a later step the Endpoint is joined to a specific Sandbox. An Endpoint can later be detached and used in a new Sandbox, which allows (for example), a container to die and be respawned without its network interface flapping. 

AFAICT there's nothing stopping a CNI plugin from doing something this sort of decoupling of veths and pod lifecycles, but I suspect many won't bother, so it sounds like this would require a significant expansion of the CNI API.

**Comment by eyakubovich** [comment]
@Symmetric Thank you for the clarification about in-tree drivers. I didn't realize that there's an HTTP interface in front of libnetwork. I assumed that libnetwork was being linked into docker daemon. Part of the confusion stems from https://github.com/docker/libnetwork/blob/master/drivers/remote/driver.go which made it look that out of tree drivers will be handled by proxying through a "remote" driver (which is not yet implemented).

However, part of concern that @philips and I have is that we don't want plugins to require a daemon (either docker or some other one that hosts the driver). In CNI model, a plugin is an executable that gets invoked when the container comes up and down -- there's no long lived process. Technically, https://github.com/appc/cni/pull/13 introduces a daemon but that's for a concrete plugin, it's not a general requirement.

As for Endpoint mobility from one sandbox to another, you're right that it's not something CNI model accommodates. I don't think a network interface flapping is a big deal since the upper layer protocols (e.g. TCP) will still flap (connections reset) as the interface moves from one namespace to the other. Obviously this is a Linux impl issue, the model does not require that but there's little use of a model that  can't be implemented (especially on Linux where most of current container excitement resides). The biggest issue with interface flapping is a potential new IP but that can get allocated. If this is something that is desired to be preserved, we should evaluate how to best accommodate.

At the same time, we will be looking on how to converge with libnetwork and possible retire CNI in favor of CNM.

**Comment by thockin** [comment]
I think Docker's dependence on daemons for plugins is unfortunate, but
given what we know about network plugins it seems plausible to have a
single piece of code work in both daemon-plugin mode and exec-plugin mode

**Comment by Symmetric** [comment]
@eyakubovich FYI some more docs for the [Remote Driver](https://github.com/squaremo/libnetwork/blob/remote_driver_docs/docs/remote.md) just landed. We're coding against this API now (as well as working on a rkt integration) - CNM is definitely a moving target :)

@thockin -- I was thinking the same thing. It would be possible to refactor the CNM interface such that all of the API calls are implemented by an executable, and the current HTTP API (required by docker remote drivers) could be implemented as a generic wrapper container that converts a binary executable into a docker-specific driver container. 

It would also be possible to build an adapter in the other direction, that turns a docker-style HTTP-daemon-based driver into a binary executable compatible with the CNI model.

**Comment by eyakubovich** [comment]
I think at this point the basic CNI model is not going to change.
