### ISSUE TITLE
passing dns resolvers out of a plugin

### ISSUE THREAD

**Issue by philips** [appc/cni#67]
We need to define the where in the returned JSON metadata a plugin can tell the caller what the DNS configuration should be. This will essentially be a priority ordered list of IP addresses:

```
"dns-resolvers": ["8.8.8.8", "8.8.4.4"]
```

**Comment by squaremo** [comment]
I can think of three appropriate ways of providing nameservers:

 * entirely out-of-band with respect to CNI (e.g., if Kubernetes runs its own DNS server);
 * in the configuration of a network;
 * supplied by an IPAM plugin.

It's a bit of a thorny one though, because it's very sensitive to the configuration of other components (e.g., you want the nameserver to supply addresses you can reach); and, you can't compose answers, so you usually have to pick one.

**Comment by philips** [comment]
@squaremo see #76
