### ISSUE TITLE
macvlan: neighbours are not aware of ARP changes

### ISSUE THREAD

**Issue by steveeJ** [appc/cni#84]
I would expect for the kernel to take care of this, but somehow it doesn't seem to work if IPs are reused. This issue stems from https://github.com/coreos/rkt/issues/1765.

**Comment by eyakubovich** [comment]
Since containers tend to be much more short lived than machines, ARP caching should be much less aggressive in the system. This is easier said than done, of course. For Linux based neighbors, setting `net.ipv4.neigh.default.gc_thresh1=0` should help (see https://groups.google.com/forum/#!searchin/coreos-user/arp/coreos-user/FG5B0PxP7Wc/4Y-JwRSOFAAJ).

An obvious improvement suggested by @steveeJ is to add an unsolicited ARP broadcast into `macvlan` plugin. Maybe even send 3 in a row (with something like 100ms delay) to reduce the chance of it getting dropped.

**Comment by steveeJ** [comment]
We should follow-up @jellonek's suggestion from https://github.com/coreos/rkt/issues/1765#issuecomment-188776317 and enable *arp_notify* on the macvlan interfaces created via CNI.

**Comment by f0** [comment]
@steveeJ 
@jellonek

any chance to get #149  merged and released ?

**Comment by jellonek** [comment]
I hope so. I have in plan to do same thing in kvm flavor, but after this on in CNI will be accessible in rkt (so after bump of dependency on appc/cni).

**Comment by steveeJ** [comment]
Fixed by #177

**Comment by nmathew** [comment]
One question on long closed issue....

why proxy_arp was enabled instead of arp_notify?

**Comment by bboreham** [comment]
@nmathew looks like it was a mistake; #586 took it out again.
